version: '3.1'

networks:
  network-zabbix:
    driver: bridge
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        networks:
            - network-zabbix
        ports:
            - '6380:6380'
        volumes:
            - './zabbix/postgres/:/var/lib/data'
        environment:
            - POSTGRES_PASSWORD=cpd@123
            - POSTGRES_DB=zabbix
            - POSTGRES_USER=zabbix
    zabbix-server:
        container_name: zabbix-server
        image: zabbix/zabbix-server-pgsql:latest
        networks:
            - network-zabbix
        links:
            - postgres
        restart: always
        ports:
            - '10051:10051'
        volumes:
            - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
        environment:
            - DB_SERVER_HOST=postgres
            - POSTGRES_DB=zabbix
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=cpd@123
        depends_on:
            - postgres
    
    zabbix-frontend:
        container_name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:latest
        networks:
            - network-zabbix
        links:
            - postgres
        restart: always
        ports:
            - '6381:8080'
            - '443:8443'
        environment:
            -   DB_SERVER_HOST=postgres
            -   POSTGRES_DB=zabbix
            -   POSTGRES_USER=zabbix
            -   POSTGRES_PASSWORD=cpd@123
            -   PHP_TZ=America/Sao_Paulo
        depends_on:
            - postgres
    
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        networks:
            - network-zabbix
        links:
            - postgres
            - zabbix-server
        restart: always
        ports:
            - '3000:3000'
        environment:
            - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
        depends_on:
            - postgres
            - zabbix-server
    
    zabbix-agent:
        container_name: zabbix-agent
        image: zabbix/zabbix-agent2:latest
        user: root
        networks:
            - network-zabbix
        links:
            - zabbix-server
        restart: always
        privileged: true
        volumes:
            - /var/run:/var/run
        ports:
            - '10050:10050'
        environment:
            - ZBX_HOSTNAME=Zabbix server
            - ZBX_SERVER_HOST=192.168.8.203